create table if not exists saved_contents (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content_id bigint references contents(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, content_id)
);

alter table saved_contents enable row level security;

create policy "Users can view their own saved contents"
  on saved_contents for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own saved contents"
  on saved_contents for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own saved contents"
  on saved_contents for delete
  using ( auth.uid() = user_id );
